// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Event struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	DurationMinutes int32        `json:"duration_minutes"`
	PassingGrade    string       `json:"passing_grade"`
	CreatedAt       sql.NullTime `json:"created_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
}

type EventQuestion struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

type Notification struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	Type      string    `json:"type"`
	IsRead    bool      `json:"is_read"`
	CreatedAt time.Time `json:"created_at"`
}

type Question struct {
	ID            uuid.UUID     `json:"id"`
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Username           string         `json:"username"`
	PasswordHash       string         `json:"password_hash"`
	FullName           string         `json:"full_name"`
	Role               string         `json:"role"`
	PhotoUrl           sql.NullString `json:"photo_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	Email              sql.NullString `json:"email"`
	EmailNotifications bool           `json:"email_notifications"`
}

type UserAnswer struct {
	ID             uuid.UUID      `json:"id"`
	ApprovalID     uuid.NullUUID  `json:"approval_id"`
	QuestionID     uuid.NullUUID  `json:"question_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type UserEventApproval struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	EventID     uuid.NullUUID  `json:"event_id"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
