// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addRandomEventQuestionsAll = `-- name: AddRandomEventQuestionsAll :exec
INSERT INTO event_questions (event_id, question_id)
SELECT $1, q.id
FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL AND q.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
ORDER BY RANDOM()
LIMIT $2
`

type AddRandomEventQuestionsAllParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) AddRandomEventQuestionsAll(ctx context.Context, arg AddRandomEventQuestionsAllParams) error {
	_, err := q.db.ExecContext(ctx, addRandomEventQuestionsAll, arg.EventID, arg.Limit)
	return err
}

const addRandomEventQuestionsByCategory = `-- name: AddRandomEventQuestionsByCategory :exec
INSERT INTO event_questions (event_id, question_id)
SELECT $1, q.id
FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.category_id = $2 AND c.deleted_at IS NULL AND q.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
ORDER BY RANDOM()
LIMIT $3
`

type AddRandomEventQuestionsByCategoryParams struct {
	EventID    uuid.UUID     `json:"event_id"`
	CategoryID sql.NullInt32 `json:"category_id"`
	Limit      int32         `json:"limit"`
}

func (q *Queries) AddRandomEventQuestionsByCategory(ctx context.Context, arg AddRandomEventQuestionsByCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addRandomEventQuestionsByCategory, arg.EventID, arg.CategoryID, arg.Limit)
	return err
}

const approveUserEvent = `-- name: ApproveUserEvent :one
UPDATE user_event_approvals
SET status = 'approved', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ApproveUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, approveUserEvent, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = true
WHERE id = $1
`

func (q *Queries) BlockSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, blockSession, id)
	return err
}

const calculateScore = `-- name: CalculateScore :one
SELECT COALESCE(SUM(q.weight), 0)::numeric as total_score
FROM user_answers ua
JOIN questions q ON ua.question_id = q.id
WHERE ua.approval_id = $1 AND ua.is_correct = true
`

func (q *Queries) CalculateScore(ctx context.Context, approvalID uuid.NullUUID) (string, error) {
	row := q.db.QueryRowContext(ctx, calculateScore, approvalID)
	var total_score string
	err := row.Scan(&total_score)
	return total_score, err
}

const checkDuplicateEvent = `-- name: CheckDuplicateEvent :one
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at, deleted_at FROM events
WHERE deleted_at IS NULL AND name = $1 AND start_time = $2 AND end_time = $3
  AND ($4::uuid IS NULL OR id <> $4::uuid)
LIMIT 1
`

type CheckDuplicateEventParams struct {
	Name      string        `json:"name"`
	StartTime time.Time     `json:"start_time"`
	EndTime   time.Time     `json:"end_time"`
	ExcludeID uuid.NullUUID `json:"exclude_id"`
}

func (q *Queries) CheckDuplicateEvent(ctx context.Context, arg CheckDuplicateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateEvent,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.ExcludeID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const checkDuplicateQuestion = `-- name: CheckDuplicateQuestion :one
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at, q.deleted_at FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL AND q.deleted_at IS NULL
  AND REGEXP_REPLACE(q.question_text, '^[[:space:][:digit:].)*#_-]+', '') ILIKE REGEXP_REPLACE($1::text, '^[[:space:][:digit:].)*#_-]+', '')
  AND ($2::uuid IS NULL OR q.id <> $2::uuid)
LIMIT 1
`

type CheckDuplicateQuestionParams struct {
	QuestionText string        `json:"question_text"`
	ExcludeID    uuid.NullUUID `json:"exclude_id"`
}

func (q *Queries) CheckDuplicateQuestion(ctx context.Context, arg CheckDuplicateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateQuestion, arg.QuestionText, arg.ExcludeID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const checkQuestionDuplicate = `-- name: CheckQuestionDuplicate :one
SELECT EXISTS(
    SELECT 1 FROM questions q
    JOIN categories c ON q.category_id = c.id
    WHERE c.deleted_at IS NULL AND q.deleted_at IS NULL
    AND LOWER(TRIM(q.question_text)) = LOWER(TRIM($1::text))
    AND ($2::uuid IS NULL OR q.id <> $2::uuid)
)
`

type CheckQuestionDuplicateParams struct {
	QuestionText string        `json:"question_text"`
	ExcludeID    uuid.NullUUID `json:"exclude_id"`
}

func (q *Queries) CheckQuestionDuplicate(ctx context.Context, arg CheckQuestionDuplicateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkQuestionDuplicate, arg.QuestionText, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL AND role = 'admin'
  AND ($1::text = '' OR full_name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountAdmins(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllActivitiesDashboard = `-- name: CountAllActivitiesDashboard :one
SELECT COUNT(*) 
FROM user_event_approvals uea
`

func (q *Queries) CountAllActivitiesDashboard(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllActivitiesDashboard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableQuestionsForEventAll = `-- name: CountAvailableQuestionsForEventAll :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE c.deleted_at IS NULL AND q.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
`

func (q *Queries) CountAvailableQuestionsForEventAll(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableQuestionsForEventAll, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableQuestionsForEventByCategory = `-- name: CountAvailableQuestionsForEventByCategory :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.category_id = $2 AND c.deleted_at IS NULL AND q.deleted_at IS NULL
  AND q.id NOT IN (SELECT question_id FROM event_questions WHERE event_id = $1)
`

type CountAvailableQuestionsForEventByCategoryParams struct {
	EventID    uuid.UUID     `json:"event_id"`
	CategoryID sql.NullInt32 `json:"category_id"`
}

func (q *Queries) CountAvailableQuestionsForEventByCategory(ctx context.Context, arg CountAvailableQuestionsForEventByCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableQuestionsForEventByCategory, arg.EventID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
WHERE deleted_at IS NULL AND ($1::text = '' OR name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountCategories(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventParticipants = `-- name: CountEventParticipants :one
SELECT COUNT(*) FROM user_event_approvals uea
JOIN users u ON u.id = uea.user_id
WHERE uea.event_id = $1
  AND ($2::text = '' OR u.username ILIKE '%' || $2::text || '%' OR u.full_name ILIKE '%' || $2::text || '%')
`

type CountEventParticipantsParams struct {
	EventID uuid.NullUUID `json:"event_id"`
	Search  string        `json:"search"`
}

func (q *Queries) CountEventParticipants(ctx context.Context, arg CountEventParticipantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventParticipants, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventQuestions = `-- name: CountEventQuestions :one
SELECT COUNT(*) FROM event_questions
WHERE event_id = $1
`

func (q *Queries) CountEventQuestions(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventQuestions, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
WHERE deleted_at IS NULL AND ($1::text = '' OR to_tsvector('indonesian', name) @@ plainto_tsquery('indonesian', $1::text))
`

func (q *Queries) CountEvents(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestions = `-- name: CountQuestions :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.deleted_at IS NULL AND c.deleted_at IS NULL
  AND ($1::int IS NULL OR q.category_id = $1::int)
  AND ($2::text = '' OR to_tsvector('indonesian', q.question_text) @@ plainto_tsquery('indonesian', $2::text))
`

type CountQuestionsParams struct {
	CategoryID sql.NullInt32 `json:"category_id"`
	Search     string        `json:"search"`
}

func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestions, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionsByCategory = `-- name: CountQuestionsByCategory :one
SELECT COUNT(*) FROM questions
WHERE category_id = $1
`

func (q *Queries) CountQuestionsByCategory(ctx context.Context, categoryID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuestionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpcomingEvents = `-- name: CountUpcomingEvents :one
SELECT COUNT(*) FROM events
WHERE end_time > NOW() AND deleted_at IS NULL
`

func (q *Queries) CountUpcomingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserApprovals = `-- name: CountUserApprovals :one
SELECT COUNT(*) FROM user_event_approvals
WHERE user_id = $1
`

func (q *Queries) CountUserApprovals(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserApprovals, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL AND role = 'peserta'
  AND ($1::text = '' OR full_name ILIKE '%' || $1::text || '%' OR email ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name, deleted_at, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, start_time, end_time, duration_minutes, passing_grade)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at, deleted_at
`

type CreateEventParams struct {
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEventQuestion = `-- name: CreateEventQuestion :exec
INSERT INTO event_questions (event_id, question_id)
VALUES ($1, $2)
`

type CreateEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) CreateEventQuestion(ctx context.Context, arg CreateEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, title, message, type)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, message, type, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Title   string    `json:"title"`
	Message string    `json:"message"`
	Type    string    `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at, deleted_at
`

type CreateQuestionParams struct {
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, refresh_token, is_blocked, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, full_name, role, photo_url, email)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	PasswordHash string         `json:"password_hash"`
	FullName     string         `json:"full_name"`
	Role         string         `json:"role"`
	PhotoUrl     sql.NullString `json:"photo_url"`
	Email        sql.NullString `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.PhotoUrl,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailNotifications,
	)
	return i, err
}

const deleteApprovalsByEventID = `-- name: DeleteApprovalsByEventID :exec
DELETE FROM user_event_approvals WHERE event_id = $1
`

func (q *Queries) DeleteApprovalsByEventID(ctx context.Context, eventID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteApprovalsByEventID, eventID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
UPDATE events
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteEventQuestion = `-- name: DeleteEventQuestion :exec
DELETE FROM event_questions
WHERE event_id = $1 AND question_id = $2
`

type DeleteEventQuestionParams struct {
	EventID    uuid.UUID `json:"event_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) DeleteEventQuestion(ctx context.Context, arg DeleteEventQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventQuestion, arg.EventID, arg.QuestionID)
	return err
}

const deleteNotificationsByMessageLike = `-- name: DeleteNotificationsByMessageLike :exec
DELETE FROM notifications
WHERE type IN ('event_approval', 'event_revocation')
AND message ILIKE '%' || $1 || '%'
`

func (q *Queries) DeleteNotificationsByMessageLike(ctx context.Context, eventName sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByMessageLike, eventName)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
UPDATE questions
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserEventApproval = `-- name: DeleteUserEventApproval :exec
DELETE FROM user_event_approvals WHERE id = $1
`

func (q *Queries) DeleteUserEventApproval(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserEventApproval, id)
	return err
}

const enrollUserToEvent = `-- name: EnrollUserToEvent :one
INSERT INTO user_event_approvals (user_id, event_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at, created_at, updated_at
`

type EnrollUserToEventParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

func (q *Queries) EnrollUserToEvent(ctx context.Context, arg EnrollUserToEventParams) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, enrollUserToEvent, arg.UserID, arg.EventID)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishExam = `-- name: FinishExam :exec
UPDATE user_event_approvals
SET is_completed = true, completed_at = NOW(), score = $2, is_passed = $3, updated_at = NOW()
WHERE id = $1
`

type FinishExamParams struct {
	ID       uuid.UUID      `json:"id"`
	Score    sql.NullString `json:"score"`
	IsPassed sql.NullBool   `json:"is_passed"`
}

func (q *Queries) FinishExam(ctx context.Context, arg FinishExamParams) error {
	_, err := q.db.ExecContext(ctx, finishExam, arg.ID, arg.Score, arg.IsPassed)
	return err
}

const getAllActivitiesDashboard = `-- name: GetAllActivitiesDashboard :many
SELECT
    u.full_name as user_name,
    u.photo_url as user_photo_url,
    e.name as event_name,
    uea.status,
    uea.is_completed,
    uea.score,
    COALESCE(uea.updated_at, uea.created_at) as activity_time,
    e.end_time as event_end_time
FROM user_event_approvals uea
JOIN users u ON uea.user_id = u.id
JOIN events e ON uea.event_id = e.id
ORDER BY COALESCE(uea.updated_at, uea.created_at) DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetAllActivitiesDashboardParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllActivitiesDashboardRow struct {
	UserName     string         `json:"user_name"`
	UserPhotoUrl sql.NullString `json:"user_photo_url"`
	EventName    string         `json:"event_name"`
	Status       string         `json:"status"`
	IsCompleted  bool           `json:"is_completed"`
	Score        sql.NullString `json:"score"`
	ActivityTime sql.NullTime   `json:"activity_time"`
	EventEndTime time.Time      `json:"event_end_time"`
}

func (q *Queries) GetAllActivitiesDashboard(ctx context.Context, arg GetAllActivitiesDashboardParams) ([]GetAllActivitiesDashboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActivitiesDashboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllActivitiesDashboardRow{}
	for rows.Next() {
		var i GetAllActivitiesDashboardRow
		if err := rows.Scan(
			&i.UserName,
			&i.UserPhotoUrl,
			&i.EventName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.ActivityTime,
			&i.EventEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEventParticipantsForExport = `-- name: GetAllEventParticipantsForExport :many
SELECT u.username, u.full_name, uea.status, uea.is_completed, uea.score, uea.is_passed, uea.started_at, uea.completed_at
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
ORDER BY uea.created_at DESC
`

type GetAllEventParticipantsForExportRow struct {
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) GetAllEventParticipantsForExport(ctx context.Context, eventID uuid.NullUUID) ([]GetAllEventParticipantsForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEventParticipantsForExport, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllEventParticipantsForExportRow{}
	for rows.Next() {
		var i GetAllEventParticipantsForExportRow
		if err := rows.Scan(
			&i.Username,
			&i.FullName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApprovalById = `-- name: GetApprovalById :one
SELECT id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at, created_at, updated_at FROM user_event_approvals WHERE id = $1
`

func (q *Queries) GetApprovalById(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalById, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalStatus = `-- name: GetApprovalStatus :one
SELECT uea.id, uea.user_id, uea.event_id, uea.status, uea.is_completed, uea.score, uea.is_passed, uea.started_at, uea.completed_at, uea.created_at, uea.updated_at, e.start_time, e.end_time, e.passing_grade,
       (SELECT COUNT(question_id)::int FROM event_questions eq WHERE eq.event_id = e.id) as question_count
FROM user_event_approvals uea
JOIN events e ON uea.event_id = e.id
WHERE uea.user_id = $1 AND uea.event_id = $2 LIMIT 1
`

type GetApprovalStatusParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

type GetApprovalStatusRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.NullUUID  `json:"user_id"`
	EventID       uuid.NullUUID  `json:"event_id"`
	Status        string         `json:"status"`
	IsCompleted   bool           `json:"is_completed"`
	Score         sql.NullString `json:"score"`
	IsPassed      sql.NullBool   `json:"is_passed"`
	StartedAt     sql.NullTime   `json:"started_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       time.Time      `json:"end_time"`
	PassingGrade  string         `json:"passing_grade"`
	QuestionCount int32          `json:"question_count"`
}

func (q *Queries) GetApprovalStatus(ctx context.Context, arg GetApprovalStatusParams) (GetApprovalStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getApprovalStatus, arg.UserID, arg.EventID)
	var i GetApprovalStatusRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartTime,
		&i.EndTime,
		&i.PassingGrade,
		&i.QuestionCount,
	)
	return i, err
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT id, name, deleted_at, created_at FROM categories
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCategoryById(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, deleted_at, created_at FROM categories
WHERE name ILIKE $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEventById = `-- name: GetEventById :one
SELECT e.id, e.name, e.start_time, e.end_time, e.duration_minutes, e.passing_grade, e.created_at, e.deleted_at, (SELECT COUNT(*)::int FROM event_questions eq WHERE eq.event_id = e.id) as total_questions
FROM events e
WHERE e.id = $1 AND e.deleted_at IS NULL LIMIT 1
`

type GetEventByIdRow struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	DurationMinutes int32        `json:"duration_minutes"`
	PassingGrade    string       `json:"passing_grade"`
	CreatedAt       sql.NullTime `json:"created_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
	TotalQuestions  int32        `json:"total_questions"`
}

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (GetEventByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i GetEventByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.TotalQuestions,
	)
	return i, err
}

const getEventTotalWeight = `-- name: GetEventTotalWeight :one
SELECT COALESCE(SUM(q.weight), 0)::numeric as total_weight
FROM event_questions eq
JOIN questions q ON eq.question_id = q.id
WHERE eq.event_id = $1
`

func (q *Queries) GetEventTotalWeight(ctx context.Context, eventID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventTotalWeight, eventID)
	var total_weight string
	err := row.Scan(&total_weight)
	return total_weight, err
}

const getExpiredEvents = `-- name: GetExpiredEvents :many
SELECT id, name, start_time, end_time, duration_minutes, passing_grade, created_at, deleted_at FROM events
WHERE end_time < NOW() AND deleted_at IS NULL
`

func (q *Queries) GetExpiredEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionById = `-- name: GetQuestionById :one
SELECT id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at, deleted_at FROM questions
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetQuestionById(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionById, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecentActivitiesDashboard = `-- name: GetRecentActivitiesDashboard :many
SELECT
    u.full_name as user_name,
    u.photo_url as user_photo_url,
    e.name as event_name,
    uea.status,
    uea.is_completed,
    uea.score,
    COALESCE(uea.updated_at, uea.created_at) as activity_time,
    e.end_time as event_end_time
FROM user_event_approvals uea
JOIN users u ON uea.user_id = u.id
JOIN events e ON uea.event_id = e.id
ORDER BY COALESCE(uea.updated_at, uea.created_at) DESC NULLS LAST
LIMIT 5
`

type GetRecentActivitiesDashboardRow struct {
	UserName     string         `json:"user_name"`
	UserPhotoUrl sql.NullString `json:"user_photo_url"`
	EventName    string         `json:"event_name"`
	Status       string         `json:"status"`
	IsCompleted  bool           `json:"is_completed"`
	Score        sql.NullString `json:"score"`
	ActivityTime sql.NullTime   `json:"activity_time"`
	EventEndTime time.Time      `json:"event_end_time"`
}

func (q *Queries) GetRecentActivitiesDashboard(ctx context.Context) ([]GetRecentActivitiesDashboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivitiesDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentActivitiesDashboardRow{}
	for rows.Next() {
		var i GetRecentActivitiesDashboardRow
		if err := rows.Scan(
			&i.UserName,
			&i.UserPhotoUrl,
			&i.EventName,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.ActivityTime,
			&i.EventEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalActiveEventsDashboard = `-- name: GetTotalActiveEventsDashboard :one
SELECT COUNT(*) FROM events
WHERE end_time > NOW() AND deleted_at IS NULL
`

func (q *Queries) GetTotalActiveEventsDashboard(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalActiveEventsDashboard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalCompletedExamsDashboard = `-- name: GetTotalCompletedExamsDashboard :one
SELECT COUNT(*) FROM user_event_approvals
WHERE is_completed = true
`

func (q *Queries) GetTotalCompletedExamsDashboard(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCompletedExamsDashboard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalParticipantsDashboard = `-- name: GetTotalParticipantsDashboard :one
SELECT COUNT(*) FROM users
WHERE role = 'peserta' AND deleted_at IS NULL
`

func (q *Queries) GetTotalParticipantsDashboard(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalParticipantsDashboard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalQuestionsDashboard = `-- name: GetTotalQuestionsDashboard :one
SELECT COUNT(*) FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.deleted_at IS NULL AND c.deleted_at IS NULL
`

func (q *Queries) GetTotalQuestionsDashboard(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalQuestionsDashboard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAnswersDetail = `-- name: GetUserAnswersDetail :many
SELECT
    ua.id as answer_id,
    ua.selected_answer,
    ua.is_correct,
    q.id as question_id,
    q.question_text,
    q.option_a,
    q.option_b,
    q.option_c,
    q.option_d,
    q.correct_answer,
    q.weight
FROM user_answers ua
JOIN questions q ON ua.question_id = q.id
WHERE ua.approval_id = $1
`

type GetUserAnswersDetailRow struct {
	AnswerID       uuid.UUID      `json:"answer_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
	QuestionID     uuid.UUID      `json:"question_id"`
	QuestionText   string         `json:"question_text"`
	OptionA        string         `json:"option_a"`
	OptionB        string         `json:"option_b"`
	OptionC        string         `json:"option_c"`
	OptionD        string         `json:"option_d"`
	CorrectAnswer  string         `json:"correct_answer"`
	Weight         int32          `json:"weight"`
}

func (q *Queries) GetUserAnswersDetail(ctx context.Context, approvalID uuid.NullUUID) ([]GetUserAnswersDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAnswersDetail, approvalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAnswersDetailRow{}
	for rows.Next() {
		var i GetUserAnswersDetailRow
		if err := rows.Scan(
			&i.AnswerID,
			&i.SelectedAnswer,
			&i.IsCorrect,
			&i.QuestionID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailNotifications,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications FROM users
WHERE username = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailNotifications,
	)
	return i, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, title, message, type, is_read, created_at FROM notifications 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications FROM users
WHERE deleted_at IS NULL AND role = 'admin'
  AND ($3::text = '' OR full_name ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.EmailNotifications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEventParticipants = `-- name: ListAllEventParticipants :many
SELECT u.id, u.username, u.full_name, u.email, uea.id as approval_id
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
`

type ListAllEventParticipantsRow struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	FullName   string         `json:"full_name"`
	Email      sql.NullString `json:"email"`
	ApprovalID uuid.UUID      `json:"approval_id"`
}

func (q *Queries) ListAllEventParticipants(ctx context.Context, eventID uuid.NullUUID) ([]ListAllEventParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEventParticipants, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEventParticipantsRow{}
	for rows.Next() {
		var i ListAllEventParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.ApprovalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, deleted_at, created_at FROM categories
WHERE deleted_at IS NULL AND ($3::text = '' OR name ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventParticipants = `-- name: ListEventParticipants :many
SELECT u.id, u.username, u.full_name, uea.id as approval_id, uea.status, uea.is_completed, uea.score, uea.is_passed
FROM users u
JOIN user_event_approvals uea ON u.id = uea.user_id
WHERE uea.event_id = $1
  AND ($4::text = '' OR u.username ILIKE '%' || $4::text || '%' OR u.full_name ILIKE '%' || $4::text || '%')
ORDER BY uea.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventParticipantsParams struct {
	EventID uuid.NullUUID `json:"event_id"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
	Search  string        `json:"search"`
}

type ListEventParticipantsRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	ApprovalID  uuid.UUID      `json:"approval_id"`
	Status      string         `json:"status"`
	IsCompleted bool           `json:"is_completed"`
	Score       sql.NullString `json:"score"`
	IsPassed    sql.NullBool   `json:"is_passed"`
}

func (q *Queries) ListEventParticipants(ctx context.Context, arg ListEventParticipantsParams) ([]ListEventParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventParticipants,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventParticipantsRow{}
	for rows.Next() {
		var i ListEventParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.ApprovalID,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventQuestions = `-- name: ListEventQuestions :many
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at, q.deleted_at FROM questions q
JOIN event_questions eq ON q.id = eq.question_id
WHERE eq.event_id = $1
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventQuestionsParams struct {
	EventID uuid.UUID `json:"event_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListEventQuestions(ctx context.Context, arg ListEventQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listEventQuestions, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.name, e.start_time, e.end_time, e.duration_minutes, e.passing_grade, e.created_at, e.deleted_at, (SELECT COUNT(*)::int FROM event_questions eq WHERE eq.event_id = e.id) as total_questions
FROM events e
WHERE e.deleted_at IS NULL AND ($3::text = '' OR to_tsvector('indonesian', e.name) @@ plainto_tsquery('indonesian', $3::text))
ORDER BY e.created_at DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

type ListEventsRow struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	DurationMinutes int32        `json:"duration_minutes"`
	PassingGrade    string       `json:"passing_grade"`
	CreatedAt       sql.NullTime `json:"created_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
	TotalQuestions  int32        `json:"total_questions"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.TotalQuestions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT q.id, q.category_id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.weight, q.created_at, q.deleted_at FROM questions q
JOIN categories c ON q.category_id = c.id
WHERE q.deleted_at IS NULL AND c.deleted_at IS NULL
  AND ($3::int IS NULL OR q.category_id = $3::int)
  AND ($4::text = '' OR to_tsvector('indonesian', q.question_text) @@ plainto_tsquery('indonesian', $4::text))
ORDER BY q.category_id ASC, q.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	CategoryID sql.NullInt32 `json:"category_id"`
	Search     string        `json:"search"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.QuestionText,
			&i.OptionA,
			&i.OptionB,
			&i.OptionC,
			&i.OptionD,
			&i.CorrectAnswer,
			&i.Weight,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT e.id, e.name, e.start_time, e.end_time, e.duration_minutes, e.passing_grade, e.created_at, e.deleted_at, (SELECT COUNT(*)::int FROM event_questions eq WHERE eq.event_id = e.id) as total_questions
FROM events e
WHERE e.end_time > NOW() AND e.deleted_at IS NULL
ORDER BY e.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUpcomingEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUpcomingEventsRow struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
	DurationMinutes int32        `json:"duration_minutes"`
	PassingGrade    string       `json:"passing_grade"`
	CreatedAt       sql.NullTime `json:"created_at"`
	DeletedAt       sql.NullTime `json:"deleted_at"`
	TotalQuestions  int32        `json:"total_questions"`
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsRow{}
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.TotalQuestions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserApprovals = `-- name: ListUserApprovals :many
SELECT e.id, e.name, e.start_time, e.end_time, e.duration_minutes, e.passing_grade, 
       (SELECT COUNT(question_id)::int FROM event_questions eq WHERE eq.event_id = e.id) as question_count,
       uea.id as approval_id, uea.status, uea.is_completed, uea.score, uea.is_passed, uea.started_at, uea.completed_at
FROM events e
JOIN user_event_approvals uea ON e.id = uea.event_id
WHERE uea.user_id = $1
ORDER BY e.start_time DESC
LIMIT $2 OFFSET $3
`

type ListUserApprovalsParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListUserApprovalsRow struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	StartTime       time.Time      `json:"start_time"`
	EndTime         time.Time      `json:"end_time"`
	DurationMinutes int32          `json:"duration_minutes"`
	PassingGrade    string         `json:"passing_grade"`
	QuestionCount   int32          `json:"question_count"`
	ApprovalID      uuid.UUID      `json:"approval_id"`
	Status          string         `json:"status"`
	IsCompleted     bool           `json:"is_completed"`
	Score           sql.NullString `json:"score"`
	IsPassed        sql.NullBool   `json:"is_passed"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListUserApprovals(ctx context.Context, arg ListUserApprovalsParams) ([]ListUserApprovalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserApprovals, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserApprovalsRow{}
	for rows.Next() {
		var i ListUserApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.PassingGrade,
			&i.QuestionCount,
			&i.ApprovalID,
			&i.Status,
			&i.IsCompleted,
			&i.Score,
			&i.IsPassed,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications FROM users
WHERE deleted_at IS NULL AND role = 'peserta'
  AND ($3::text = '' OR full_name ILIKE '%' || $3::text || '%' OR email ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.PhotoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.EmailNotifications,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}

const revokeUserEvent = `-- name: RevokeUserEvent :one
UPDATE user_event_approvals
SET status = 'revoked', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, event_id, status, is_completed, score, is_passed, started_at, completed_at, created_at, updated_at
`

func (q *Queries) RevokeUserEvent(ctx context.Context, id uuid.UUID) (UserEventApproval, error) {
	row := q.db.QueryRowContext(ctx, revokeUserEvent, id)
	var i UserEventApproval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.IsCompleted,
		&i.Score,
		&i.IsPassed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveUserAnswer = `-- name: SaveUserAnswer :one
INSERT INTO user_answers (approval_id, question_id, selected_answer, is_correct)
VALUES ($1, $2, $3, $4)
ON CONFLICT (approval_id, question_id) 
DO UPDATE SET 
    selected_answer = EXCLUDED.selected_answer, 
    is_correct = EXCLUDED.is_correct
RETURNING id, approval_id, question_id, selected_answer, is_correct, created_at
`

type SaveUserAnswerParams struct {
	ApprovalID     uuid.NullUUID  `json:"approval_id"`
	QuestionID     uuid.NullUUID  `json:"question_id"`
	SelectedAnswer sql.NullString `json:"selected_answer"`
	IsCorrect      sql.NullBool   `json:"is_correct"`
}

func (q *Queries) SaveUserAnswer(ctx context.Context, arg SaveUserAnswerParams) (UserAnswer, error) {
	row := q.db.QueryRowContext(ctx, saveUserAnswer,
		arg.ApprovalID,
		arg.QuestionID,
		arg.SelectedAnswer,
		arg.IsCorrect,
	)
	var i UserAnswer
	err := row.Scan(
		&i.ID,
		&i.ApprovalID,
		&i.QuestionID,
		&i.SelectedAnswer,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const setStartedAt = `-- name: SetStartedAt :exec
UPDATE user_event_approvals SET started_at = NOW(), updated_at = NOW() WHERE id = $1 AND started_at IS NULL
`

func (q *Queries) SetStartedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setStartedAt, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, deleted_at, created_at
`

type UpdateCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2, start_time = $3, end_time = $4, duration_minutes = $5, passing_grade = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, start_time, end_time, duration_minutes, passing_grade, created_at, deleted_at
`

type UpdateEventParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	PassingGrade    string    `json:"passing_grade"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.PassingGrade,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.PassingGrade,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET category_id = $2, question_text = $3, option_a = $4, option_b = $5, option_c = $6, option_d = $7, correct_answer = $8, weight = $9
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, question_text, option_a, option_b, option_c, option_d, correct_answer, weight, created_at, deleted_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID     `json:"id"`
	CategoryID    sql.NullInt32 `json:"category_id"`
	QuestionText  string        `json:"question_text"`
	OptionA       string        `json:"option_a"`
	OptionB       string        `json:"option_b"`
	OptionC       string        `json:"option_c"`
	OptionD       string        `json:"option_d"`
	CorrectAnswer string        `json:"correct_answer"`
	Weight        int32         `json:"weight"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.CategoryID,
		arg.QuestionText,
		arg.OptionA,
		arg.OptionB,
		arg.OptionC,
		arg.OptionD,
		arg.CorrectAnswer,
		arg.Weight,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.QuestionText,
		&i.OptionA,
		&i.OptionB,
		&i.OptionC,
		&i.OptionD,
		&i.CorrectAnswer,
		&i.Weight,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, full_name = $3, role = $4, photo_url = $5, email = $6, email_notifications = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, password_hash, full_name, role, photo_url, created_at, updated_at, deleted_at, email, email_notifications
`

type UpdateUserParams struct {
	ID                 uuid.UUID      `json:"id"`
	Username           string         `json:"username"`
	FullName           string         `json:"full_name"`
	Role               string         `json:"role"`
	PhotoUrl           sql.NullString `json:"photo_url"`
	Email              sql.NullString `json:"email"`
	EmailNotifications bool           `json:"email_notifications"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.PhotoUrl,
		arg.Email,
		arg.EmailNotifications,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.EmailNotifications,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPhoto = `-- name: UpdateUserPhoto :exec
UPDATE users SET photo_url = $2 WHERE id = $1
`

type UpdateUserPhotoParams struct {
	ID       uuid.UUID      `json:"id"`
	PhotoUrl sql.NullString `json:"photo_url"`
}

func (q *Queries) UpdateUserPhoto(ctx context.Context, arg UpdateUserPhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhoto, arg.ID, arg.PhotoUrl)
	return err
}
