// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthCache is an autogenerated mock type for the AuthCache type
type AuthCache struct {
	mock.Mock
}

// DeleteSession provides a mock function with given fields: ctx, sessionID
func (_m *AuthCache) DeleteSession(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSession provides a mock function with given fields: ctx, sessionID
func (_m *AuthCache) GetSession(ctx context.Context, sessionID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSession provides a mock function with given fields: ctx, sessionID, userID, durationMinutes
func (_m *AuthCache) SetSession(ctx context.Context, sessionID uuid.UUID, userID uuid.UUID, durationMinutes int) error {
	ret := _m.Called(ctx, sessionID, userID, durationMinutes)

	if len(ret) == 0 {
		panic("no return value specified for SetSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, sessionID, userID, durationMinutes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthCache creates a new instance of AuthCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthCache {
	mock := &AuthCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
