// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlcgen "github.com/odealidj/pramuka-CAT/backend/internal/adapters/repository/sqlcgen"

	uuid "github.com/google/uuid"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// BlockSession provides a mock function with given fields: ctx, id
func (_m *AuthRepository) BlockSession(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BlockSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: ctx, arg
func (_m *AuthRepository) CreateSession(ctx context.Context, arg sqlcgen.CreateSessionParams) (sqlcgen.Session, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 sqlcgen.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateSessionParams) (sqlcgen.Session, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateSessionParams) sqlcgen.Session); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *AuthRepository) CreateUser(ctx context.Context, arg sqlcgen.CreateUserParams) (sqlcgen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateUserParams) (sqlcgen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateUserParams) sqlcgen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSession provides a mock function with given fields: ctx, id
func (_m *AuthRepository) GetSession(ctx context.Context, id uuid.UUID) (sqlcgen.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 sqlcgen.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlcgen.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlcgen.Session); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *AuthRepository) GetUserById(ctx context.Context, id uuid.UUID) (sqlcgen.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sqlcgen.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) sqlcgen.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *AuthRepository) GetUserByUsername(ctx context.Context, username string) (sqlcgen.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
